export enum Player {
    Andy = "andy",
    Bree = "bree",
    Brandon = "brandon",
    Brian = "brian",
    Cade = "cade",
    Darwin = "darwin",
    Elke = "elke",
    Josh = "josh",
    Lindsey = "lindsey",
    // Sequential = "sequential",
    Sophie = "sophie",
    Steve = "steve",
    Steven = "steven",
    Sun = "sun",
    Susi = "susi",
    Susu = "susu",
    Tang = "tang",
    Yang = "yang",
}

export const PLAYERS = Object.values(Player);

export const PLAYER_COLORS: Record<Player, string[]> = {
    [Player.Andy]: ["#f6de64", "#2f5c81", "#4e95c3", "#cfd0cc"],
    [Player.Bree]: ["#5c64f4", "#6c7cf4", "#acb4fc", "#d7dafc"],
    [Player.Brandon]: ["#9192be", "#aa3824", "#ead67d", "#c8a592"],
    [Player.Brian]: ["#757e8a", "#447e8a", "#5c9da4", "#ffffff"],
    [Player.Cade]: ["#dbff9e", "#0f793e", "#479d56", "#91cb9e"],
    [Player.Darwin]: ["#cddbff", "#7f8ceb", "#ffc561", "#fffd8f"],
    [Player.Elke]: ["#60111f", "#9b2127", "#e59755", "#decdc2"],
    [Player.Josh]: ["#faa61a", "#fead5b", "#fde7c1", "#ffffff"],
    [Player.Lindsey]: ["#92ced5", "#d1988d", "#ebd5ca", "#ffffff"],
    // [Player.Sequential]: ["#a6735d", "#4e6b32", "#7b8769", "#dce1cc"],
    [Player.Sophie]: ["#b15c5d", "#daa379", "#dab79a", "#ffffff"],
    [Player.Steve]: ["#2180ba", "#43815f", "#7ca7a0", "#a3cdd9"],
    [Player.Steven]: ["#f8f4a6", "#e69470", "#8bbece", "#eec6c7"],
    [Player.Sun]: ["#dccdca", "#20878c", "#58bfc4", "#85d3e8"],
    [Player.Susi]: ["#556371", "#bf8d68", "#e7b897", "#f7c1d6"],
    [Player.Susu]: ["#cb759c", "#987d68", "#afa392", "#ffffff"],
    [Player.Tang]: ["#cea891", "#998e91", "#f2d5cf", "#ffffff"],
    [Player.Yang]: ["#c62c38", "#c64049", "#e86f68", "#ffffff"],
};

export const PLAYER_TAG: Record<Player, string> = {
    [Player.Andy]: "Candysan",
    [Player.Brandon]: "JHardRTolkien",
    [Player.Bree]: "Brioche",
    [Player.Brian]: "brianwoohoo",
    [Player.Cade]: "RhythmKing",
    [Player.Darwin]: "ChzGorditaCrunch",
    [Player.Elke]: "Uzumaki 好き",
    [Player.Josh]: "bot001341",
    [Player.Lindsey]: "aylindsay",
    // [Player.Sequential]: "Sequential",
    [Player.Sophie]: "chushberry",
    [Player.Steve]: "Selintt",
    [Player.Steven]: "youngsmasher",
    [Player.Sun]: "sun",
    [Player.Susi]: "SusTwins",
    [Player.Susu]: "danielscutiegf",
    [Player.Tang]: "tangy",
    [Player.Yang]: "Tyblerone",
};

export enum ValorantMap {
    Ascent = "Ascent",
    Bind = "Bind",
    Split = "Split",
    Icebox = "Icebox",
    Pearl = "Pearl",
    Fracture = "Fracture",
    Lotus = "Lotus",
    Haven = "Haven",
    Breeze = "Breeze",
}

export const MAP_COLORS: Record<ValorantMap, string> = {
    Ascent: "#a79cd0",
    Bind: "#b9835d",
    Split: "#808488",
    Icebox: "#48609a",
    Pearl: "#3cb7c6",
    Fracture: "#4f6740",
    Lotus: "#faa3d1",
    Haven: "#8f5142",
    Breeze: "#649ab1",
};
