export const PLAYERS = [
    "andy",
    "brandon",
    "brian",
    "cade",
    "darwin",
    "josh",
    "lindsey",
    "sequential",
    "sophie",
    "steve",
    "steven",
    "sun",
    "susi",
    "susu",
    "tang",
    "yang",
];

export const PLAYER_COLORS = {
    andy: "#f6de64",
    brandon: "#384268",
    brian: "#757e8a",
    cade: "#dbff9e",
    darwin: "#cddbff",
    josh: "#faa61a",
    lindsey: "#92ced5",
    sequential: "#a6735d",
    sophie: "#b15c5d",
    steve: "#2180ba",
    steven: "#f8f4a6",
    sun: "#dccdca",
    susi: "#334455",
    susu: "#cb759c",
    tang: "#cea891",
    yang: "#c62c38",
};
